import sys
import os
import pandas as pd

srcdir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, srcdir)

from protein_feature_vectors import Calculator  # noqa: E402

proteins = Calculator()
proteins.display_feature_types()
proteins.get_feature_vectors(
    "QSOrder", file=f"{srcdir}/data_examples/multi.fa"
)
assert isinstance(proteins.encodings, pd.DataFrame)

seqs = {
    "A12345": "LVTIKIGGQLKEALLDTGADDTVLEDMHLPGKWKPKMIGGIGGFIKVRQYDQILVEICGH"
    + "KAIGTVLVGPTPVNIIGRNLLTQIGCTLNFEMEKEGKISKIGPENPYNTPIFAIKKKDST"
    + "KWRKLVDFRELNKRTQDFWEVQLGIPHPAGLKKKKSVTVLDVGDAYFSVPLDEDFRKYTA"
    + "FTIPSTNNETPGIRYQYNVLPQGWKGSPAIFQSSMTKILEPFRKQNPDIVIYQYMDDLYV"
    + "GSDLEIGQHRIKVEELRQHLLRWGLTTPDKKHQKEPPFLWMG",
    "B3QQG6": "MQETSATITAERKHSHVDVCLNRPVCFDGQDTGLDAWRFEHNAAPEIDFAEIDLTA"
    + "EFLGHAIGMPLMISSMTGGYGDALALNRTLAEAAERFRIPLGVGSMRQALEGNSHRESFSIVRSSA"
    + "PSVPIFANIGAPEVAAGLSREQLSTLVELIEADGLIVHLNPAQELFQPEGSTNFRGFLDRLHDITA"
    + "TINVPVIAKEVGCGISAPLASKLADAGVKAIDVAGAGGISWQKVEECRYLDRFGNEERFSPSALDEF"
    + "LNWGIPTAECLTGIAALKEKSPEYGSLAVISSGGIRNGLDVAKSIALGADIAASAQHLLKALRAGTLEE"
    + "TIRTWANDLRAAMFLTGSATTAQLKHAPIYRKP",
    "short": "M",
}

proteins.get_feature_vectors("QSOrder", pdict=seqs)
print(proteins.encodings)
